# Generated by Django 2.0 on 2021-03-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=20, unique=True)),
                ('Password', models.CharField(default='Password', max_length=80)),
                ('Role', models.CharField(max_length=20)),
                ('Otp', models.IntegerField(max_length=20)),
                ('is_actiive', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
